const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Ahmad Akhtar";
const email = "Email";
const emailHint = "Email@gmail.com";
const password = "Password";
const reTypePassword = "Retype Password";
const name = "Name";
const nameHint = "Ahmad Akhtar";
const passwordHint = "**********";
const forgotPassword = "ForgotPassword";
const login = "Login";
const signUp = "SignUp";
const createNewAccount = "Create New Account";
const loginWith = "Login With ";
const privacyPolicy = " & Pivacy Policy ";
const termAndCondition = "Terms And Conditions";
const alreadyHaveAccount = "Already have Account? ";
const home = "Home";
const categories = "Categories";
const cart = "Cart";
const account = "Account";
const searchAnyThing = "Search anyThing";
const todayDeal = "Today's Deal";
const flashSale = "Flash Sale";
const topSeller = "Top Seller";
const brand = "Brand";
const topCategories = "Top Categories";
const featuredCategories = "Featured Categories";

const womenDress = "Women Dress";
const girlsWatches = "Girl Watches";
const mobilePhone = "Mobile Phone";
const boysGlasses = "Boys Glasses";
const tShirts = "T Shirts";
const girlsDress = "Girls Dress";

const featuredProduct = "Featured Products";

const womenClothing = "Woman Clothing",
menClothingFashoin="Men Clothing Fashion",
computerAccessories="Computer Accessories" ,
autoMobile="Auto Mobiles",
kidsToys="Kids Toys",
jeweleries="Jewellerie",
sports="Sports",
cellPhone="Cell Phone",
furniture="Furniture"
;
